using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Polsih
{
    public static class Words
    {
        public static string[] words = {
            "tak",
            "nie",
            "poniedziałek",
            "wtorek",
            "środa",
            "czwartek",
            "piątek",
            "sobota",
            "niedziela",
            "granatowy",
            "niebieski",
            "czarny",
            "biały",
            "szary",
            "czerwony",
            "zielony",
            "pomarańczowy",
            "żółty",
            "bezbarwny",
            "przezroczysty",
            "różowy",
            "rudy",
            "szmaragdowy",
            "srebrny",
            "na przodzie",
            "od tyłu",
            "na wierzchu",
            "na dole",
            "pod",
            "nad",
            "przód",
            "za",
            "lewy",
            "prawy",
            "z lewej",
            "z prawej",
            "dzień dobry",
            "dobry wieczór",
            "cześć",
            "Co słychać",
            "Miło Cię poznać",
            "Ratunku!",
            "Nie rozumiem po polsku",
            "Ile to kosztuje",
            "Do widzenia",
            "dziękuję",
            "samolot",
            "bilet",
            "paszport",
            "granica",
            "dokumentacja",
            "certyfikat",
            "traktat",
            "rachunek",
            "konto bankowe",
            "waluta",
            "pieniądze",
            "cena",
            "zapłacić",
            "apartament",
            "podłoga",
            "dom",
            "adres",
            "gospodarz",
            "najemca",
            "pokój",
            "kuchnia",
            "łazienka",
            "balkon",
            "winda",
            "drabina",
            "okno",
            "Internet",
            "woda",
            "elektryczność",
            "sklep",
            "produkt",
            "plastikowa torba",
            "karta",
            "gotówka",
            "sprzedawca",
            "kasa",
            "kantor",
            "bilon",
            "bezgotówkowy"
        };
    }
}
